webtalk_init -webtalk_dir /home/mdomingu/FPGAPrototypingByVerilogExamples/2.9.2Gate_level_binary_decoder/2.9.2Gate_level_binary_decoder.sim/sim_1/behav/xsim/xsim.dir/decoder3_8block_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Feb 10 13:43:51 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018833" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1a02bd51-88dd-429a-a2e7-2e43356f8694" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "20e23efcdefa4bc7a0f5bbfb35644d21" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2443.356 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "129744_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2279235018 -regid "" -xml /home/mdomingu/FPGAPrototypingByVerilogExamples/2.9.2Gate_level_binary_decoder/2.9.2Gate_level_binary_decoder.sim/sim_1/behav/xsim/xsim.dir/decoder3_8block_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/mdomingu/FPGAPrototypingByVerilogExamples/2.9.2Gate_level_binary_decoder/2.9.2Gate_level_binary_decoder.sim/sim_1/behav/xsim/xsim.dir/decoder3_8block_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/mdomingu/FPGAPrototypingByVerilogExamples/2.9.2Gate_level_binary_decoder/2.9.2Gate_level_binary_decoder.sim/sim_1/behav/xsim/xsim.dir/decoder3_8block_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
